### ISSUE TITLE
Can't embed PNG as base64

### ISSUE THREAD

**Issue by jopacicdev** [barryvdh/laravel-dompdf#116]
Hey, I'm trying to embed a base64 value of PNG image into the document, via:

`<img src="{{ $sig }}" />` where `$sig = 'data:image/png;base64,iVBORw0K.......'`

But this gives me a large X-box with message:

```
Data-URI could not be parsed
data:data:image/png;base64,iVBORw0KGg..........
```

How can I display embedded images in PDF, without having to actually upload the somewhere?

**Comment by ebarriosbloonde** [comment]
Hi, have you solved this problem? :)

**Comment by GaurangGhinaiya** [comment]
@ebarriosbloonde 

`Image not found or type unknown`
when i try to load image as base46 i am getting this in pdf

**Comment by Asimov500** [comment]
I am also getting the same problem. Have you managed to sort it. I am loading images from outside the root folder and need this to work.

**Comment by andrespaz1991** [comment]
Lo único que se puede hacer es enviar desde otro formulario por medio de POST aquí una explicación más clara https://stackoverflow.com/questions/37328139/is-it-possible-to-export-a-google-chart-using-dompdf

**Comment by jopacicdev** [comment]
Since the error says:
```
Data-URI could not be parsed
data:data:image/png;base64,iVBORw0KGg..........
```

You should probably omit one 'data:' and it will render fine.

**Comment by tripexito** [comment]
Hi, I am having issues to download pdf file generated with png images, in chrome download dialog shows as .html instead of .pdf

![image](https://user-images.githubusercontent.com/2284599/95668543-df324b00-0b4b-11eb-8e99-16068759850f.png)

![image](https://user-images.githubusercontent.com/2284599/95668559-0721ae80-0b4c-11eb-9fed-c290a5caeda1.png)

I've been trying using images as base64 and its working the pdf file download in chrome but the images does not showing on pdf file downloaded. In Firefox Pdf Viewer there's no issues. Please tell how can I solve. Thanks.
