### ISSUE TITLE
How to solved this ?

### ISSUE THREAD

**Issue by sapitidur** [barryvdh/laravel-dompdf#158]
Non-static method Barryvdh\DomPDF\PDF::loadView() should not be called statically, assuming $this from incompatible context

 $pdf=PDF::loadView('adm-sales.pdf',array('send'=>$sendpdf))->setPaper('A4');
 return $pdf->download('send order.pdf');

**Comment by bebnev** [comment]
This happens because you are namespacing the wrong PDF class.
You are namespacing `Barryvdh\DomPDF\PDF` and try to use this class as "Facade" which is wrong.
So there are two posiible ways to solve your problem:
1) Setting namespace to the facade:
```php
use Barryvdh\DomPDF\Facade as PDF;
```
2) Using alias (only if you add PDF alias to the `app.php` in the `alias` section):
```php
use PDF;
```

**Comment by barryvdh** [comment]
Indeed, use the Facade.

**Comment by sagar720** [comment]
Non-static method Barryvdh\DomPDF\PDF::loadView() should not be called statically
