### ISSUE TITLE
DOMPDF_TEMP_DIR configuration ignored?

### ISSUE THREAD

**Issue by brazorf** [barryvdh/laravel-dompdf#267]
Hey there.
I've just changed the setting to 

```
"DOMPDF_TEMP_DIR" => storage_path('app/'),
```

but still i'm getting the error

```
file_exists(): open_basedir restriction in effect. File(/tmp/log.htm) is not within the allowed path(s): (/srv/foo.com/)
```

storage/ is owned by www-data and it has the right permissions.

Anybody knows why?

**Comment by sinceritysolutionsbangalore** [comment]
Did you solve the issue? I have the same problem

**Comment by brazorf** [comment]
Nope, i've temporarily changed my php open_basedir setting, but didn't get the `DOMPDF_TEMP_DIR` working properly.

**Comment by merrant** [comment]
I know your not supposed to change vendor files but in my case what helped was changing the Options.php in vendor/dompdf/dompdf/src/ 
In the constructor I changed $this->setTempDir(sys_get_temp_dir()); to $this->setTempDir(storage_path('app/')); and that helped.

**Comment by joseevillasmil** [comment]
Hello guys, I fixed it this way.

You have to edit this 2 files.

1) vendor/dompdf/options.php
2) config/dompdf.php

**IN OPTIONS**

find this line

>  "DOMPDF_TEMP_DIR" =>anything

and change the path in order to be save it like this.

> "DOMPDF_TEMP_DIR" => storage_path('tmp'), 

after that 

**IN config/dompdf.php**
find this line

> $this->setLogOutputFile($this->getTempDir() . DIRECTORY_SEPARATOR . "log.htm");

and replace it by

> $this->setLogOutputFile(storage_path('tmp/'). "log.htm");

Now, the last you have to do is to create 2 folders in the root/storage in order to be used by the application.

root/
----- storage/
---------------tmp/
---------------fonts/

Create te storage/tmp and storage/fonts in order to be used by the app and give them the right permissions. after this you can run the pdf creator and it should work.

FYI
if you dont find the config/dompdf.php file, try runing aritisian to export the config file from vendor firectory to the config directory.
the command is the nextone

`php artisan vendor:publish --provider="Barryvdh\DomPDF\ServiceProvider"`

if you are using another version of laravel (<5) go to the documentation link to get the correct command line.

https://github.com/barryvdh/laravel-dompdf

Have a good code day. Jose Villasmil.

**Comment by britweb** [comment]
Yeah this is messed up, can confirm that joseevillasmil's solution works but we cannot rely on hacking the core dompdf library.

**Comment by cortier** [comment]
Why is this closed? This was never resolved. 

config/dompdf.php option:
`"temp_dir" => `

Does nothing. Why this hasn't been resolved?

**Comment by tim-xergy** [comment]
Can we have this re-opened please as this is still an issue

**Comment by ronlinet** [comment]
I don't think that this has anything to do with `tmp_dir` what try to do here is change the tmp `logOutputFile` for `index.htm` . This is the code that works in my case 
        `$pdf->setOptions(['logOutputFile' => storage_path('app/dompdf/' . 'index.html')] );`.
