### ISSUE TITLE
Laravel 5.3 pdf rendering issue

### ISSUE THREAD

**Issue by praveenkumart** [barryvdh/laravel-dompdf#299]
Call to undefined method Barryvdh\DomPDF\PDF::setOrientation()

I am getting the above error on saving pdf.

PDF::loadHTML($flight_plan_pdf_content)
                ->setPaper('a4')
                ->setOrientation('portrait')
                ->save($filePath . $fileName);

About mentioned is my code.

the same code is working with laravel 5.2 and "barryvdh/laravel-dompdf": "0.6.*",

**Comment by stephenflynn** [comment]
I'm a little late to the party but:
Having a look at the code I see: `public function setPaper($paper, $orientation = 'portrait')`

So I believe this will work: 

`PDF::loadHTML($flight_plan_pdf_content)
->setPaper('a4', 'portrait')
->save($filePath . $fileName);`

Because it's the default you could leave 'portrait' out.

**Comment by praveenkumart** [comment]
Thanks for the help

Closing it
