### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-dompdf#339]
We have two servers that our software is deployed to at the moment. On produces the PDF's correctly, the other seems to ignore alot of the CSS.

I have attached both the working and broken PDF's produced by the same code.

[broken.pdf](https://github.com/barryvdh/laravel-dompdf/files/916630/broken.pdf)
[working.pdf](https://github.com/barryvdh/laravel-dompdf/files/916631/working.pdf)

Any ideas what could be causing this?

**Comment by pdiveris** [comment]
Hi,

I ran into similar problems with PDFs rendering fine (i.e. with the images showing) on a "live" server over https  and no images on the local dev environment. The issue was down to the fact that the certificate on my local dev environment being issued by me was invalid. Dompdf itself will check whether `isRemoteEnabled` is set to true and then, depending on your environment, it will try to load the remote content. When I say depending on your environment, it will check if you have `allow_url_fopen` set to on in your PHP ini, in which case it will attempt a `file_get_contents($uri, null, $context, $offset);`; 

If not, it will revert to using curl. All this is happening around lines 823 to 860 of Helpers.php of **dompdf** itself. Even though there are two methods implemented to set the context (`set_http_context` and `setHttpContext` ever gets called. 

Because I have `allow_url_fopen` set to On, I worked around this by creating a http context and passing it over. This can be done with something like:

```
      $arrContextOptions = array(
        "ssl" => array(
          "verify_peer" => false,
          "verify_peer_name" => false,
        ),
      );
      ```
and then passing it over to Dompdf's setHttpContext like  `$dompdf->setHttpContext(stream_context_create($httpContext)`

Now, the question is where does one pass it over? What I did is that I added a method in Barry's laravel-dompf's PDF.php file:

```
  /**
   * Set http context e.g. SSL options
   *
   * @param array $httpContext
   */
    public function setHttpContext($httpContext = []){
      if (!empty($httpContext)) {
        $this->dompdf->setHttpContext(stream_context_create($httpContext));
      }
      return $this;
    }```

so that I now invoke the PDF generation like this

```
        return \PDF::setHttpContext($arrContextOptions)
          ->loadHTML($stream)
          ->save(storage_path("artifacts/dompdf/v2_$file_name.pdf"))
          ->stream($id . '.pdf')
          ;
```

This works fine, bit it obviously only works with file_get_contents. Similar work would need to be done for curl, but what I didn't want to do was to touch dompdf itself. 

I've cloned Barry's laravel-dompdf and I was just about to create an issue describing this and asking Barry if I could commit/push my work and do a Pull Request.
