### ISSUE TITLE
Image is not loaded in next page of PDF

### ISSUE THREAD

**Issue by jkpatil211** [barryvdh/laravel-dompdf#340]
Hello

I am loading a view and storing the output pdf on AWS S3 using following code

    $pdf = PDF::loadView('productPDF1', ['products' => $this->products]);
    $filePath = 'downloadPDF/'.bin2hex(openssl_random_pseudo_bytes(8)).'_'.time().'.pdf';
    Storage::disk('s3')->put($filePath, $pdf->output(), 'public');
    $fileUrl = Storage::disk('s3')->url($filePath);

The images in view are loaded from s3 and are public.
My problem is,  images are loaded on first page but  on next page.
Please help its urgent
Thank you

**Comment by jkpatil211** [comment]
@barryvdh Plz help me to solve this issue.

**Comment by danilosantosdev** [comment]
@barryvdh I'm having the same problem. 
How can we solve the issue?

@jkpatil211 Do you solve it?

**Comment by wmcmurray** [comment]
Hey @jkpatil211 and @danilosantosdev , does the first `<img>` tag of the pdf look fine and all others seems to be invisible ? I just had this problem and it turned out the cause was because I added some unsupported CSS in my rendered page !

Then I realized the lib used by this project is not webkit based and basically don't support CSS 3.

Then I used https://github.com/barryvdh/laravel-snappy instead and I've been happy ever since.

To see if you have unrecognized CSS you could turn on debug like this : 
```php
PDF::setOptions(['debugCss' => true]);
PDF::loadHTML($html)->setWarnings(true)->save('myfile.pdf')
```

**Comment by danilosantosdev** [comment]
Hey @wmcmurray, thanks for your response.

My "solution" was migrate to laravel snappy too, it supplied all my needs.

Hugs.

**Comment by iwasherefirst2** [comment]
I used `img { display: block !important; }` which caused them to be invisible. Removing that line fixed it for me.
