### ISSUE TITLE
Don't show Khmer Unicode (UTF-8)?

### ISSUE THREAD

**Issue by thearabbit** [barryvdh/laravel-dompdf#40]
I load view with Khmer Uicode, but it don't show:

``` php
// in routes
Route::get(
    'pdf',
    function () {
        $pdf = PDF::loadView('pdf_view');
        return $pdf->download();
    }
);

// in view
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
Welcome to កម្ពុជា
</body>
</html>
```

**Comment by kristoff2016** [comment]
still have this issue

**Comment by kirykr** [comment]
@kristoff2016 
i user this package it works the same way as this library (this library works great for other languages but not khmer font).

- `composer require niklasravnsborg/laravel-pdf`
- It has a well doc about font installation: https://mpdf.github.io/
- after installing the package, got to its repo https://github.com/niklasravnsborg/laravel-pdf read the instruction.
- run `php artisan vendor:publish` select the library from the command prompt. You'll got the `pdf.php` in `config` directory
- Now you need to choose appropriate khmer fonts from the doc https://mpdf.github.io/fonts-languages/available-fonts-v6.html
- In the doc it recommends from two khmer font websites. You must download the fonts from the websites otherwise the fonts will not display correctly.
- download the fonts and store somewhere in the project - by default the `config/pdf.php` choose `resources/fonts` directory 
And here is my setup in the `pdf.php`
```php
'font_path' => base_path('resources/fonts/'),
  'font_data' => [
    "khmerosmoul" => [/* Khmer */
      'R' => "KhmerOSmuol.ttf",
      'useOTL' => 0xFF,
    ],
    "khmerosmoullight" => [/* Khmer */
      'R' => "KhmerOSmuollight.ttf",
      'useOTL' => 0xFF,
    ],
    "khmerosbokor" => [/* Khmer */
      'R' => "KhmerOSBokor.ttf",
      'useOTL' => 0xFF,
    ],
    "khmerosmoulpali" => [/* Khmer */
      'R' => "KhmerOSmuolpali.ttf",
      'useOTL' => 0xFF,
      'useKashida' => 75
    ]
    // ...add as many as you want.
  ]
```
