### ISSUE TITLE
DomPdf is not working on shared host

### ISSUE THREAD

**Issue by aimalamiri** [barryvdh/laravel-dompdf#444]
When my application was on my localhost it was working but when I downloaded my website to a shared host it's not working and the issue is when I click on a link to download my pdf report its redirecting me to the html page instead of downloading the pdf file and I don't know how to fix it.

**Comment by ashokgrg** [comment]
Hello friend, I think it's a font issue so please check the laravel.log file and check the necessary font inside storage/fonts folder. when  dompdf run it will create md5 ttf file like
35635251311-ff1a6dda-001d-11e8-8efe-af18a7386347.ttf so locally generated this type of file may not work in shared hosting or this type of font may be missing. This solution will be at first check laravel.log because we can find cause the error from the log file. If the issue is because of the font you can upload all fonts in shared hosting or you can delete automatically generate md5 naming font files and run the system then the system will automatically generate the necessary fonts. But I am not sure your problem will be solved or not.

**Comment by aimalamiri** [comment]
No I'm not using a different font just I've added the sans-serif font to the body font family style property I don't know whats the problem but I'm sure its not because of the font

**Comment by irenehavsa** [comment]
Hi, did you find the solution? I face the exact same problem at the moment and haven't found any working solution. 

This code below works fine on my local machine but not on the shared hosting. Instead of showing the PDF, it redirects to the same page. 
`return $pdf->stream("invoice.pdf", array('Attachment'=>0));`

I have also tried modify the code and add `exit;` after the PDF stream, but it only gave me a blank page. 
`$pdf->stream("invoice.pdf", array('Attachment'=>0));
exit;`

Any leads would be really helpful. Thanks :)

**Comment by gazsmith10** [comment]
I'm having this issue
