### ISSUE TITLE
How to use external css

### ISSUE THREAD

**Issue by FireflyStars** [barryvdh/laravel-dompdf#553]
I have been using laravel-dompdf for generating pdf.
But It does not work well for me.
Css style  doesnt work.
Please solve this issue.

**Comment by janainadcacaca** [comment]
Olá @FireflyStars 

Passei também por este problema e espero que isso ajude você. Estou usando Laravel 5.3 com o DomPDF v0.8.2 e consegui aplicar CSS inline e aplicar mudanças de fontes utilizando o @font-face. 

Dos testes que que fiz referenciar o arquivo CSS externo demora muito para carregar fazendo com que fique inviável para utilizar, já com o CSS inline funcione bem. 
Para que a fonte externa funcione ao gerar o arquivo PDF você deve criar uma pasta com o nome 'fonts' em storage. 

Então o diretório/caminho deve ficar desta forma: storage/fonts/

Não precisa colocar nenhum arquivo de fonte dentro desta pasta, o Dompdf utiliza somente para carregar os arquivos como cache antes de exportar o PDF. Então é importante que este diretório tenha permissão de escrita.

Em meu config/filesystems.php estou utilizando disco publico desta forma tenho uma pasta 'fonts' dentro de /public/ onde tenho as fontes que desejo utilizar. Em meu CSS referencio os arquivos como pode observar:

            <style type="text/css">

                @charset "utf-8";

                @font-face {
                    font-family: 'Source Sans Pro', sans-serif;
                    src: url({{ storage_path('fonts/SourceSansPro-Regular.ttf') }});
                    font-weight: 400;
                    font-style: normal;
                }

                @font-face {
                    font-family: 'Source Sans Pro', sans-serif;
                    src:url({{ storage_path('fonts/SourceSansPro-ExtraLight.ttf') }});
                    font-weight: 300;
                    font-style: normal;
                }

              body {
                    margin-left: 60px;
                    margin-right: 60px;
                    background-color: #fff;
                    font-family: 'Source Sans Pro', sans-serif;
                    font-weight: 400;
                    font-style: normal;
                }

Também tive problema para carregar imagens, consegui solucionar transformando a imagem para base_64 e colocando o caminho completo (full path) do diretório.

    <?php
    $path = 'img/logo.svg';
    //$path = 'img/logo.png';
    $type = pathinfo($path, PATHINFO_EXTENSION);
    $data = file_get_contents($path);
    $base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
    ?>

No HTML:

     <td align="left" style="width: 20%;">
             <img src="{{ $base64 }}" alt="Logo" class="logo" style="width: 100px; height:80px;"/>
               <h2>Logo</h2>
      </td>


Testei imagens utilizando PNG e SVG, com png mesmo colocando width e height menor do que a proporção da imagem quando transformava em PDF ficava distorcido. Não tive este problema ao utilizar SVG.

Espero que isto te ajude! Abraços.

------------------------------------------------------------------------------------------------------------------------------------------


Hello @FireflyStars

I also went through this problem and hope it is help you. I'm using Laravel 5.3 with DomPDF v0.8.2 and managed to apply inline CSS and apply font changes using @font-face.

Of the tests that I did reference the external CSS file takes a lot to load making it impractical to use, since inline CSS works well. 
For the external font to work with the PDF file, you must create a folder named 'fonts' in storage directory.

So the directory should look like this: storage/fonts/

You do not need to put any font files inside this folder, Dompdf only uses to load the files as cache before exporting the PDF. So it is important that this directory is writable.

In my config/filesystems.php I'm using public disk this way I have a 'fonts' folder inside /public/ where I have the fonts I want to use. In my CSS I refer to the files as you can see:

            <style type="text/css">

                @charset "utf-8";

                @font-face {
                    font-family: 'Source Sans Pro', sans-serif;
                    src: url({{ storage_path('fonts/SourceSansPro-Regular.ttf') }});
                    font-weight: 400;
                    font-style: normal;
                }

                @font-face {
                    font-family: 'Source Sans Pro', sans-serif;
                    src:url({{ storage_path('fonts/SourceSansPro-ExtraLight.ttf') }});
                    font-weight: 300;
                    font-style: normal;
                }

              body {
                    margin-left: 60px;
                    margin-right: 60px;
                    background-color: #fff;
                    font-family: 'Source Sans Pro', sans-serif;
                    font-weight: 400;
                    font-style: normal;
                }


Also I had problem to work with images, I managed to solve transforming the image to base_64 and putting the full path of the directory:

<? php
$ path = 'img / logo.svg';
// $ path = 'img / logo.png';
$ type = pathinfo ($ path, PATHINFO_EXTENSION);
$ data = file_get_contents ($ path);
$ base64 = 'data: image /'. $ type. '; base64, '. base64_encode ($ data);
?>

Without HTML:

     <td align="left" style="width: 20%;">
             <img src="{{ $base64 }}" alt="Logo" class="logo" style="width: 100px; height:80px;"/>
               <h2>Logo</h2>
      </td>


I tested images using PNG and SVG, with png even putting width and height smaller than the aspect ratio when rendering into PDF was distorted. I did not have this problem when using SVG.

Hope this helps you! Hugs.

**Comment by muhammadSaferagic** [comment]
maybe, you can create a one file in views folder. copy all css code in file /public/css/app.css then paste to file that you created in views folder ex: /views/css.blade.php paste it in tag <style> so you call css.blade.php by include file to your viewPDF file that will be download. thank's.

css.blade.php:
`
<style type="text/css">
     //paste here
</style>
`

include by templating blade in your pdf view:
`
@include('css')
`
