### ISSUE TITLE
Bootstrap 3

### ISSUE THREAD

**Issue by karnash** [barryvdh/laravel-dompdf#59]
fail when i use the BT 3 and Laravel dont works fine..

**Comment by derylihs** [comment]
same here, why i can use BT3 css?

and for table align fail to

**Comment by barryvdh** [comment]
You guys do understand that this is a php library trying to parse and understand all complex css/html rules? You can't expect some php library to render exactly like Chrome when you throw in a few thousand lines of css..

As I said, if you do want that, try this: https://github.com/barryvdh/laravel-snappy

**Comment by wmcmurray** [comment]
@barryvdh Maybe you could specify this on top of the readme ?

Because I just spent hours trying to fix bugs only to realize this project don't support CSS 3 :disappointed:  ...maybe it's the fact that this project has more stars than `laravel-snappy` on github, maybe it's the name "laravel-dompdf" that does not evoke it's "php-only or non-webkit" characteristic enough. I just felt that this project was more capable so I used it without really digging into the technologies used under the hood...
