### ISSUE TITLE
add dynamic header on each page

### ISSUE THREAD

**Issue by yashpalchhajer** [barryvdh/laravel-dompdf#696]
Hi, is there any way to add dynamic header content for each page, right now if I add header it is adding same in all page,
But my need is to add different content in header for different pages.
Also need to skip header for specific pages in same PDF.
Can anyone suggest anything for this.
I am using below method to add header

```
<style>
header {
     position: fixed;
     top: -35px;
     left: 0px;
     right: 0px;
     height: 50px;
 }
</style>
<header>
    <table width="100%" class="header_table" style="border-bottom: 3px solid blue;">
        <thead>
            <tr width="100%">
            <th width="50%" class="text-left">Student 1</th>
                <th width="50%" class="text-right">Class 1</th>
            </tr>
        </thead>
    </table>
</header>
<main>main content of pdf </main>
```
here in place of ```Student 1``` and ```Class 1``` I wanted to set different student names for diff pages.

**Comment by PHPGuus** [comment]
Hi @yashpalchhajer ,

Since this is more of a community question, as opposed to an issue, I would urge you to raise this question at OpenStack, or eventually ask the maintainers of DOMPDF if there is suitable forum available where you can ask this question.

Please be aware that this package merely makes DOMPDF/DOMPDF available to Laravel artisans in a Laravel way.

Best regards,
Guus

@barryvdh This issue can be closed.
