### ISSUE TITLE
skip page number printing in footer on specific pages of same pdf.

### ISSUE THREAD

**Issue by yashpalchhajer** [barryvdh/laravel-dompdf#698]
I am using below code to set page number, and that is working fine.
`<script type="text/php">
    if (isset($pdf)) {
            $pdf->page_script('
            $size = 10;
            $font = $fontMetrics->getFont("{{$template['font']}}");
            $current_page = $PAGE_NUM-1;
            $total_pages = $PAGE_COUNT-1;
            $width = $fontMetrics->get_text_width($current_page, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) - 70;
            $y = $pdf->get_height() - 35;
            $pdf->text($x, $y, "$current_page", $font, $size);
        ');
    }
</script>`

also I work around to skip first page in pdf.

But now my requirement is to skip printing page number on some specific pages in same pdf.

Like I am creating pdf of some data of students and each student has it's title page.
So on title page I don't want to print page number and rest of all page should have page number.

can any one suggest a way to do this.

**Comment by PHPGuus** [comment]
Hi @yashpalchhajer ,

Since this is more of a community question, as opposed to an issue, I would urge you to raise this question at OpenStack, or eventually ask the maintainers of DOMPDF if there is suitable forum available where you can ask this question.

Please be aware that this package merely makes DOMPDF/DOMPDF available to Laravel artisans in a Laravel way.

Best regards,
Guus

@barryvdh This issue can be closed.
