### ISSUE TITLE
stream() doesnt work for me in Chrome ...

### ISSUE THREAD

**Issue by dmarko484** [barryvdh/laravel-dompdf#7]
Thanks for such excellent dompdf binding!!  I'm using it with Lataver 4, things are working smooth, I can download PDF without problem ...  but stream() is working for me in Firefox but doesnt work in Chrome for me. In Chrome it just opens empty PDF and thats all. Is this just me or overall problem?

**Comment by Naeem-Ullah-Bj** [comment]
stream method in working

**Comment by mohamed-aitlqadi** [comment]
stream method is not working !

**Comment by Naeem-Ullah-Bj** [comment]
if you have any download manager like (IDM) install in you PC then it will
not work.
please uninstall the download manager and it will work.

**Comment by mohamed-aitlqadi** [comment]
@Naeem-Ullah-Bj thanks for the answer, but NO, I don't have it.
@barryvdh

**Comment by Naeem-Ullah-Bj** [comment]
> @Naeem-Ullah-Bj thanks for the answer, but NO, I don't have it.
> @barryvdh

check extensions in chrome and disable it

**Comment by emilas44** [comment]
@barryvdh I just wanted to add to this because I have a similar problem and didn't want to open a new "Issue"

It's that when I use ```return $pdf->stream('test.pdf');```

It shows the pdf file properly in both Firefox and Chrome

And then when I want to download it in Firefox works
But in Chrome I get an error: "Failed - Network Error" down in the download tab. And I can't get to see what is the exact error... the network tab in dev extension is empty, nothing happens....

Maybe you have an idea or some advice what could I try?

**Comment by emilas44** [comment]
@barryvdh Hi, so I just wanted to say that I "solved" the problem.... I can't really say solved because there is something about Chrome that makes problem when you try to download a generated .pdf file when it's fetched with POST request.

So my solution was to send a GET request and then it shows the generated .pdf file and then I can download it.

**Comment by tripexito** [comment]
Hi, I am having issues to download pdf file generated with png images, in chrome download dialog shows as .html instead of .pdf
![image](https://user-images.githubusercontent.com/2284599/95645352-82c02480-0a94-11eb-99bf-f57434ca66b1.png)
I've been trying using images as base64 and its working the pdf file download in chrome but the images does not showing on pdf file downloaded. In Firefox Pdf Viewer there's no issues. Please tell how can I solve. Thanks.
