### ISSUE TITLE
setOptions method breaks image loading

### ISSUE THREAD

**Issue by daviderix88** [barryvdh/laravel-dompdf#793]
When you set options, images are not loaded:

Controller:
```
$pdf = App::make('dompdf.wrapper');
$pdf->loadView('print.certificate', $evaluation)->setPaper('a4', 'landscape');
$pdf->setOptions([]); // it does not matter what options you set
```

View:
`<img src="{{ public_path('images/certificate_tpl.jpg') }}">
`
Result:
Image not found or type unknown

If you remove the setOptions, the image is loaded.

Tested on: Laravel 8, Debian Linux, Laravel development server (php artisan serve), PHP 7.4.

**Comment by betoflakes** [comment]
I was stuck in the same problem. I added setOptions and the images not load anymore.

**Comment by vladski** [comment]
The issue is that method setOptions resets ALL options to default values from vendor, including "chroot". That is directory, that Dompdf is allowed to access files from, which is in dompdf.php config file set to Laravel base path, but by setOptions it is reset to vendor root dir.

Do not use setOptions unless you want set ALL of the options. Get current Options object and set what you need like this:  

```
$pdf->getDomPDF()->getOptions()->setIsPhpEnabled(true);
```
