### ISSUE TITLE
ErrorException: file_put_contents(/tmp/log.htm): failed to open stream: Permission denied 

### ISSUE THREAD

**Issue by ezekel** [barryvdh/laravel-dompdf#807]
Hi @barryvdh 
I'm running this using Jobs but my Jobs always get fail

`ErrorException: file_put_contents(/tmp/log.htm): failed to open stream: Permission denied in /var/www/myproject/vendor/dompdf/dompdf/src/Dompdf.php:903`

version in composer
`"barryvdh/laravel-dompdf": "^0.9.0"`

**Comment by Biostate** [comment]
In HTTPD conf you need to add /tmp to the open_base_dir. i solve in this way.

**Comment by colbyalbo** [comment]
@ezekel 
not sure this will help you or not but here is what i did, I was facing the same issue. I have a job that is dispatched each morning from Cron. This is a directory permissions issue on the server, which I preferred not to change since I don't need the log output file, and this is the only PDF i'm generating from the CLI.
I  added the `setOptions` method , and set the  `logOutputFile` to null. This returns out of the method within DOMPDF that handles the output file.

Before:
` $pdf = PDF::loadView('pdf.myview', compact('data'));`

After:
` $pdf = PDF::setOptions(['logOutputFile' => null,])->loadView('pdf.myview', compact('data'));`

Note: if there are any image assets included in the view , they won't be included any longer. (i'm guessing this has to do with not generating the output file )
What I did, was convert them to Data URI's, I only had one.

maybe try this a workaround.

**Comment by Abderrahmene-Hnd** [comment]
ntoma na9ssin ntoma
